runtime: java19
instance_class: F1
entrypoint: java -jar target/wordlebot-0.0.1-SNAPSHOT.jar

env_variables:
  SPRING_PROFILES_ACTIVE: prod

handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always
